### ISSUE TITLE
User mistake or path bug?

### ISSUE THREAD

**Issue by TeoTwawki** [AdamGagorik/pydarkstar#1]
"The main scripts are located in ./path/to/pydarkstar/apps. They should work if run from that directory"
ok. I try and run scrub and I get:
```
C:\pydarkstar\apps>scrub.py
Traceback (most recent call last):
  File "C:\pydarkstar\apps\scrub.py", line 22, in <module>
    import pydarkstar.scrub.ffxiah
ImportError: No module named scrub.ffxiah

C:\pydarkstar\apps>scrub.py --force
Traceback (most recent call last):
  File "C:\pydarkstar\apps\scrub.py", line 22, in <module>
    import pydarkstar.scrub.ffxiah
ImportError: No module named scrub.ffxiah
```
I see what I think is the file it wants to import in a diff subdir. Did I miss something?

**Comment by AdamGagorik** [comment]
I will try running it in a terminal like you have (on Windows I only ever ran it through an IDE).

Off the top of my head, it looks like you aren't specifying the python interpreter before the script name - though I don't see why that would matter.  I had not designed them to be executable.

**Comment by TeoTwawki** [comment]
I tried
```
python scrub.py --force
```
from my
```
C:\pydarkstar\apps
```
dir and saw exact same result.

**Comment by AdamGagorik** [comment]
Hmm I just did:

```bash
C:\Users\Adam\Desktop\pydarkstar\apps>python .\scrub.py --help
usage: scrub.py [-h] [--verbose] [--silent] [--overwrite] [--backup] [--save]
                [--force] [--threads -1] [--urls [url [url ...]]]
                [--itemids [itemids [itemids ...]]] [--stock01 5]
                [--stock12 5]
                [stub]

Create item database.

positional arguments:
  stub                  output file stub

optional arguments:
  -h, --help            show this help message and exit
  --verbose             report debug, info, and error
  --silent              report error only
  --overwrite           overwrite output file
  --backup              backup output file
  --save                save config file (and exit)
  --force               start from scratch
  --threads -1          number of cpu threads to use
  --urls [url [url ...]]
                        a list of category urls
  --itemids [itemids [itemids ...]]
                        a list of item ids
  --stock01 5           default stock for singles
  --stock12 5           default stock for stacks
```

Are you using python3 by chance?

**Comment by AdamGagorik** [comment]
I am using:

Python 2.7.6 :: Anaconda 2.1.0 (64-bit)

**Comment by TeoTwawki** [comment]
I'm on 2.7.something whatever was latest for 2.7 line as of last month.

**Comment by AdamGagorik** [comment]
See if it runs from the directory above.

C:\Users\Adam\Desktop\pydarkstar>python .\apps\scrub.py --help

**Comment by TeoTwawki** [comment]
Same result.
```
C:\pydarkstar>python .\apps\scrub.py --help
Traceback (most recent call last):
  File ".\apps\scrub.py", line 22, in <module>
    import pydarkstar.scrub.ffxiah
ImportError: No module named scrub.ffxiah
```

**Comment by AdamGagorik** [comment]
I changed some import statements around, pull then try it again.  Let me know if it works.  It really should be...

**Comment by TeoTwawki** [comment]
```
C:\pydarkstar\apps>python .\scrub.py --help
Traceback (most recent call last):
  File ".\scrub.py", line 17, in <module>
    import pydarkstar
  File "C:\pydarkstar\pydarkstar\__init__.py", line 6, in <module>
    pydarkstar.logutils.setError()
AttributeError: 'module' object has no attribute 'logutils'
```

**Comment by AdamGagorik** [comment]
A new error, that's always a good sign.

I will change all the imports to relative, I have a feeling this will fix things.

**Comment by AdamGagorik** [comment]
All updated to relative.  If this doesn't work I am just baffled.  I will blame Windows.

**Comment by TeoTwawki** [comment]
ARG!
```
C:\pydarkstar\apps>python .\scrub.py --help
Traceback (most recent call last):
  File ".\scrub.py", line 17, in <module>
    import pydarkstar
  File "C:\pydarkstar\pydarkstar\__init__.py", line 3, in <module>
    from . import logutils
ImportError: cannot import name logutils
```

**Comment by AdamGagorik** [comment]
Ok...

I will try and look at it tomorrow, bedtime for now.

**Comment by AdamGagorik** [comment]
So...

I think I have figured it out.  There are a few options.

# SHORT VERSION

1. git pull
2. create batch scripts

 ```bat
 C:\pydarkstar>python .\makebin.py
 ```

3. run batch script

 ```bat
 C:\pydarkstar>cd .\bin
 C:\pydarkstar\bin>.\scrub.bat --help
 ```

# LONG VERSION

1.  I (or you) move the scripts out of that app folder and put them in the top level directory.

 ```cmd
 C:\pydarkstar\apps>move C:\pydarkstar\apps\scrub.py C:\pydarkstar\
 C:\pydarkstar\apps>cd ..
 C:\pydarkstar>python scrub.py --help
 ```

 They will work there, if not I think your python configuration is abnormal.

2.  I (or you) wrap the app scripts in batch scripts that set the PYTHONPATH before calling them.

 * you would create a bat script, **with the correct paths**
  ```bat
 @ECHO OFF
 set PYTHONPATH=%PYTHONPATH%;C:\Users\Adam\Desktop\pydarkstar
 python C:\Users\Adam\Desktop\pydarkstar\apps\scrub.py %*
  ```
 * *optionally*, add **PAUSE** at the end to keep the terminal open after, if running by "clicking in explorer"

 To use the apps you would call the batch scripts instead
 ```bat
 C:\pydarkstar\bin>.\scrub.bat --help
 ```

**There is a makebin.py script in the top level directory that will construct the batch scripts for you.**

Try either of these things and let me know if they work.  If they do not work, I am interested in the following:

1.  python version
 ```bat
 C:\Users\Adam>python --version
 Python 2.7.6 :: Anaconda 2.1.0 (64-bit)
 ```

2.  python location
 ```bat
 C:\Users\Adam>where python
 C:\Users\Adam\Anaconda\python.exe
 ```

3.  PYTHONPATH
 ```bat
 C:\Users\Adam>echo %PYTHONPATH%

 %PYTHONPATH%
 ```

4.  PATH
 ```bat
 C:\Users\Adam>echo %PATH%
                                                                                                                                                          
 C:\Users\Adam\Desktop\ConEmuPack.140723;
 C:\Users\Adam\Desktop\ConEmuPack.140723\ConEmu;
 C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
 C:\Perl64\site\bin;C:\Perl64\bin;
 C:\P
 C:\WINDOWS\system32;
 C:\WINDOWS;
 C:\WINDOWS\System32\Wbem;
 C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
 C:\Program Files (x86)\Lua\5.1;
 C:\Program Files (x86)\Lua\5.1\clibs;
 C:\Program bin;
 C:\Ruby200-x64\bin;
 C:\Users\Adam\Anaconda;
 C:\Users\Adam\Anaconda\Scripts;
 C:\Program Files (x86)\CMake 2.8\bin                                                                  
  ```

5.  sys.path
 ```bat
 C:\Users\Adam>python
 Python 2.7.6 |Anaconda 2.1.0 (64-bit)| (default, May 27 2014, 15:00:33) [MSC v.1500 64 bit (AMD64)] on win32
 Type "help", "copyright", "credits" or "license" for more information.
 Anaconda is brought to you by Continuum Analytics.
 Please check out: http://continuum.io and https://binstar.org
 >>> import sys
 >>> print('\n'.join(sys.path))
 
 C:\Users\Adam\Anaconda\python27.zip
 C:\Users\Adam\Anaconda\DLLs
 C:\Users\Adam\Anaconda\lib
 C:\Users\Adam\Anaconda\lib\plat-win
 C:\Users\Adam\Anaconda\lib\lib-tk
 C:\Users\Adam\Anaconda
 C:\Users\Adam\Anaconda\lib\site-packages
 C:\Users\Adam\Anaconda\lib\site-packages\PIL
 C:\Users\Adam\Anaconda\lib\site-packages\Sphinx-1.2.3-py2.7.egg
 C:\Users\Adam\Anaconda\lib\site-packages\win32
 C:\Users\Adam\Anaconda\lib\site-packages\win32\lib
 C:\Users\Adam\Anaconda\lib\site-packages\Pythonwin
 C:\Users\Adam\Anaconda\lib\site-packages\runipy-0.1.1-py2.7.egg
 C:\Users\Adam\Anaconda\lib\site-packages\setuptools-5.8-py2.7.egg
 >>> quit()
 ```

**Comment by TeoTwawki** [comment]
Now works when run from C:\pydarkstar. Even without using batches or setting %PYTHONPATH%

I always ran your older version on DarkStars forums in a similar batch so I'm in familiar territory here, and plan to use a shortcut to a batch file for starting the broker.

Also my Python version is 2.7.8

My python install is in C:\Python27 and both that dir and the scripts subdir are in my winblows path.

**Comment by AdamGagorik** [comment]
winblows lol...

Glad it works, closing this.
