### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Morbiusdream** [AdamGagorik/pydarkstar#12]
Everytime i try to use command this happens

(base) C:\Users\Morbius\Documents\DSP_programs\Pydarkstar\pydarkstar\bin>"C:\Users\Morbius\Anaconda3\python.exe" .\broker.py --help
Traceback (most recent call last):
  File ".\broker.py", line 12, in <module>
    import pydarkstar
  File "C:\Users\Morbius\Documents\DSP_programs\Pydarkstar\pydarkstar\pydarkstar\__init__.py", line 42, in <module>
    from . import common
  File "C:\Users\Morbius\Documents\DSP_programs\Pydarkstar\pydarkstar\pydarkstar\common.py", line 8
    def create_path(*args, absolute=True, dt_fmt='%Y_%m_%d_%H_%M_%S', dt=None, **kwargs):
                                  ^
SyntaxError: invalid syntax

**Comment by AdamGagorik** [comment]
As you say, I think this appears when you try to execute things with Python2 instead of Python3.  You can always check what you are running by executing python --version in the terminal.
