### ISSUE TITLE
Bin Py File Errors

### ISSUE THREAD

**Issue by Deakstok** [AdamGagorik/pydarkstar#14]
I am getting errors with trying to alter the prices with Alter.py/

C:\Users\ASUS1>cd C:\Users\ASUS1\Desktop\pydarkstar\bin

C:\Users\ASUS1\Desktop\pydarkstar\bin>C:\path\python .\alter.py
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: config     = config.yaml
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: verbose    = True
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: silent     = False
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: data       = ['items.csv']
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: stub       = items
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: overwrite  = True
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: backup     = True
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: all        = False
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: lambda_    = None
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: match      = None
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: itemids    = []
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: show       = False
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: scrub      = False
[2018-12-14 20:40:09][13860][INFO ]: (0x45b9c90) Options: set        = []
[2018-12-14 20:40:09][13860][DEBUG]: (0x46ac710) ItemList: init
[2018-12-14 20:40:09][13860][INFO ]: (0x46ac710) ItemList: loading item data...
[2018-12-14 20:40:09][13860][INFO ]: (0x46ac710) ItemList: load items.csv
[2018-12-14 20:40:10][13860][INFO ]: 0 items selected
[2018-12-14 20:40:10][13860][ERROR]: caught unhandled excetion
Traceback (most recent call last):
  File "C:\Users\ASUS1\Desktop\pydarkstar\pydarkstar\logutils.py", line 45, in capture
    yield
  File ".\alter.py", line 21, in <module>
    pydarkstar.apps.alter.run.main()
  File "C:\Users\ASUS1\Desktop\pydarkstar\pydarkstar\apps\alter\run.py", line 68, in main
    raise RuntimeError('no itemids passed or found!')
RuntimeError: no itemids passed or found!
[2018-12-14 20:40:10][13860][INFO ]: exit

**Comment by AdamGagorik** [comment]
I think the script is complaining that you have not passed any command line arguments.  Try running --help to see what you can do.  To be honest the alter script is the least developed and you may find it easier to just edit the items.csv file in excel.
