### ISSUE TITLE
Unable to Scrub the AH

### ISSUE THREAD

**Issue by evenmonkeys** [AdamGagorik/pydarkstar#15]
```
[2019-02-10 14:23:49,594][ 3996][INFO ]: (0x29b5588) Options: config     = config.yaml
[2019-02-10 14:23:49,594][ 3996][INFO ]: (0x29b5588) Options: verbose    = True
[2019-02-10 14:23:49,595][ 3996][INFO ]: (0x29b5588) Options: silent     = False
[2019-02-10 14:23:49,595][ 3996][INFO ]: (0x29b5588) Options: stub       = items
[2019-02-10 14:23:49,595][ 3996][INFO ]: (0x29b5588) Options: overwrite  = False
[2019-02-10 14:23:49,595][ 3996][INFO ]: (0x29b5588) Options: backup     = True
[2019-02-10 14:23:49,596][ 3996][INFO ]: (0x29b5588) Options: stock01    = 3
[2019-02-10 14:23:49,596][ 3996][INFO ]: (0x29b5588) Options: stock12    = 3
[2019-02-10 14:23:49,596][ 3996][INFO ]: (0x29b5588) Options: itemids    = ????
[2019-02-10 14:23:49,596][ 3996][INFO ]: (0x29b5588) Options: urls       = ????
[2019-02-10 14:23:49,597][ 3996][DEBUG]: (0x3d940f0) FFXIAHScrubber: init
[2019-02-10 14:23:49,598][ 3996][DEBUG]: (0x3d940f0) FFXIAHScrubber: forcing redownload of data
[2019-02-10 14:23:49,598][ 3996][DEBUG]: (0x3d940f0) FFXIAHScrubber: getting category urls
[2019-02-10 14:23:49,598][ 3996][DEBUG]: (0x3d940f0) FFXIAHScrubber: open http://www.ffxiah.com/browse
[2019-02-10 14:23:49,600][ 3996][ERROR]: urlopen failed (attempt 1)
Traceback (most recent call last):
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\scrubbing\scrubber.py", line 33, in soup
    handle = urlopen(url)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2019-02-10 14:24:01,679][ 3996][ERROR]: the maximum urlopen attempts have been reached
[2019-02-10 14:24:01,681][ 3996][ERROR]: caught unhandled excetion
Traceback (most recent call last):
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\logutils.py", line 45, in capture
    yield
  File "C:\Users\Highwind\Desktop\ah\bin\scrub.py", line 21, in <module>
    pydarkstar.apps.scrub.run.main()
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\apps\scrub\run.py", line 35, in main
    data = scrubber.scrub(force=True, threads=-1, urls=opts.urls, ids=opts.itemids)
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\scrubbing\ffxiah.py", line 63, in scrub
    urls = self._get_category_urls()
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\scrubbing\ffxiah.py", line 194, in _get_category_urls
    soup = self.soup(path)
  File "C:\Users\Highwind\Desktop\ah\pydarkstar\scrubbing\scrubber.py", line 33, in soup
    handle = urlopen(url)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
[2019-02-10 14:24:01,704][ 3996][INFO ]: exit
```

**Comment by AdamGagorik** [comment]
I am not able to reproduce this using the current Conda environment.  I would have to know more about your setup (python --version) to figure out if this behavior is related to that.

![image](https://user-images.githubusercontent.com/5294486/59556791-e9aff500-8f96-11e9-9613-71d27f468bb9.png)
