### ISSUE TITLE
Periodic fail

### ISSUE THREAD

**Issue by TeoTwawki** [AdamGagorik/pydarkstar#3]
On a clean AH table and delivery box table, it runs for some hours before problems happen. 

This big pile of errors requires wiping the AH table to clear get it running again:
```
[2015-01-18 01:49:26][ 8636][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\database.py", line 46, in scoped_session
    session.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 776, in c
ommit
    self.transaction.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 377, in c
ommit
    self._prepare_impl()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 357, in _
prepare_impl
    self.session.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1919, in
flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2037, in
_flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60,
in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in
_flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 372, i
n execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 526, i
n execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 60, i
n save_obj
    mapper, table, update)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 518,
in _emit_update_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 729, in e
xecute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in
_execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 826, in _
execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 958, in _
execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1159, in
_handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 199, in r
aise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 951, in _
execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 436, i
n do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 135, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 274, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 714, in quer
y
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 865, in _rea
d_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1062, in rea
d
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 830, in _rea
d_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 348, in chec
k_error
    raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 116, in raise_mysql_
exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 109, in _check_mysql
_exception
    raise errorclass(errno,errorvalue)
IntegrityError: (IntegrityError) (1048, u"Column 'quantity' cannot be null") 'UP
DATE auction_house SET buyer_name=%s, sale=%s, sell_date=%s WHERE auction_house.
id = %s' ('AH-Bot', 2000, 1421545766.137, 95785)
```

Possibly related question and issue: does the tool clear its own gil deliveries out of the delivery box? I've heard from DSP devs that there is a limit to how many entries can accumulate, and that just nulling the seller won't prevent it. 

I and another server using this tool have both seen players not receiving their gil after awhile, and resetting delivery box table seems to return things to normal for some time before the problem repeats, same as the above errors are temporarily relived by clearing the auction house table. However, there have been changes in DarkStar with the delivery box, so that could be a DSP bug and not a pydarkstar bug. Edit: 99% sure deliv box thing is NOT a pydakrstar prob...

**Comment by AdamGagorik** [comment]
It doesn't touch the delivery box table at all.  Are you saying people are putting up things for auction, not picking up their gil, and too many entries appear in their personal delivery box?

I'm guessing the delivery_box table is updated automagically (by darkstar or by mysql?) after the auction_house table changes.

The part about "Column 'quantity' cannot be null" is a delivery_box column.  I guess in this context it means the amount of gil being sent.  So, for whatever reason, the amount of gil sent is less than or equal to zero.

It would be nice to know the itemid of the item being bought here.  You already cleared your AH table?  If not check row 95785.  Then look in the items.csv and make sure the data looks consistant - like is the price01 == 0 or pirce12 == 0? (Which shouldn't happen)

This is all I can think of for now.

**Comment by TeoTwawki** [comment]
That row is itemID 17216, Light Crossbow, spice info says 2000 gil. 


Whats happening with delivery is people say they list the item and no gil arrives even though when they check the history it says the broker did buy it. I suspect the current implementation of the delivery system in DSP doesn't stop the responsible party but instead stops **everyone** from getting deliveries and one or more players overloaded the delivery box queue. I'll try and test that theory later.

**Comment by AdamGagorik** [comment]
Hmm.  If theres anything in pydarkstar that needs changed to fix it, let me know.  Sounds like it's a darkstar thing though?

**Comment by TeoTwawki** [comment]
Yeah looks like, and if my error messages were related to deliv box, then it likely caused both. Closing this for now and if I find there is a real pydarkstar bug, I'll reopen or make a new issue here. I won't have more info till Tuesday, giving people time to get their stuff out and put away before I wipe tables again.

**Comment by TeoTwawki** [comment]
Just wanted to let you know, it was indeed a combination of flaws in DarkStar's delivery system, and in the case of the other server I helped, leftover garbage in deliv box table from a past AH tool they had used which caused them to trip that problem with a limited global delivery queue much more often and rapidly, which helped us pinpoint it.  DarkStar lead dev has bumped up the max queue size as a short term solution (no change to pydarkstar needed). At some point their search/ah server needs a major overhaul.

**Comment by AdamGagorik** [comment]
Thanks for letting me know.
