### ISSUE TITLE
RuntimeError: SQL Failed

### ISSUE THREAD

**Issue by ChiyuriYui** [AdamGagorik/pydarkstar#30]
hi i have been trying to resolve this issue when i run the broker.py

if you could help plz

thanx 
wes

(pydarkstar) D:\FFXI Server\AH\bin>.\broker.py
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: config     = config.yaml
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: verbose    = True
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: silent     = False
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: hostname   = 127.0.0.1
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: database   = dspdb
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: username   = root
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: password   = ????
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: fail       = True
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: data       = ['items.csv']
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: name       = Zusa
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: restock    = 3600
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a475bc40b8) Options: tick       = 30
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796aaf98) Database: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd198) Manager: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd0f0) Browser: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd128) Cleaner: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd320) Seller: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd1d0) Buyer: init
[2022-01-29 04:51:51][MainProcess][MainThread][DEBUG]: (0x2a4796cd160) ItemList: init
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a4796cd160) ItemList: loading item data...
[2022-01-29 04:51:51][MainProcess][MainThread][INFO ]: (0x2a4796cd160) ItemList: load items.csv
[2022-01-29 04:51:52][MainProcess][MainThread][INFO ]: starting main loop...
[2022-01-29 04:51:52][MainProcess][MainThread][DEBUG]: time=0000000000.0 s last restock=0000000000.0 s next restock=0000003600.0 s
[2022-01-29 04:51:52][MainProcess][MainThread][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 146, in _do_get
    self._dec_overflow()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'dspdb'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FFXI Server\AH\pydarkstar\database.py", line 45, in scoped_session
    yield session
  File "D:\FFXI Server\AH\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "D:\FFXI Server\AH\pydarkstar\auction\manager.py", line 68, in buy_items
    for row in q:
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 2887, in __iter__
    return self._iter().__iter__()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 146, in _do_get
    self._dec_overflow()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'dspdb'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-01-29 04:51:52][MainProcess][MainThread][ERROR]: caught unhandled excetion
Traceback (most recent call last):
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 146, in _do_get
    self._dec_overflow()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'dspdb'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\FFXI Server\AH\pydarkstar\database.py", line 45, in scoped_session
    yield session
  File "D:\FFXI Server\AH\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "D:\FFXI Server\AH\pydarkstar\auction\manager.py", line 68, in buy_items
    for row in q:
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 2887, in __iter__
    return self._iter().__iter__()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 96, in __init__
    else engine.raw_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 476, in checkout
    rec = pool._do_get()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 146, in _do_get
    self._dec_overflow()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 143, in _do_get
    return self._create_connection()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 371, in __init__
    self.__connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'dspdb'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\FFXI Server\AH\pydarkstar\logutils.py", line 47, in capture
    yield
  File "D:\FFXI Server\AH\bin\broker.py", line 21, in <module>
    pydarkstar.apps.broker.run.main()
  File "D:\FFXI Server\AH\pydarkstar\apps\broker\run.py", line 53, in main
    manager.buy_items(itemdata=idata)
  File "D:\FFXI Server\AH\pydarkstar\auction\manager.py", line 115, in buy_items
    self.debug('skipping row %d', row.id)
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\FFXI Server\AH\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "C:\Users\weswa\anaconda3\envs\pydarkstar\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\FFXI Server\AH\pydarkstar\database.py", line 61, in scoped_session
    raise RuntimeError('SQL Failed')
RuntimeError: SQL Failed
[2022-01-29 04:51:52][MainProcess][MainThread][INFO ]: exit

(pydarkstar) D:\FFXI Server\AH\bin>

**Comment by AdamGagorik** [comment]
The key takeaway in all that text is:
‘Unknown database 'dspdb'‘

1.  Did someone change the name of the database?
2. Is it possible your database is not running or setup correctly?
3. Does pydarkstar have your SQL credentials?

Unfortunately there’s no real way for me to reproduce this behavior, it’s been a long time since I’ve had any of this running personally.

**Comment by ChiyuriYui** [comment]
thank you so much for the response, and thank you for the information. i did the set up as per the instruction but i don't remember database name that was there. ill look into it, thanx

**Comment by ChiyuriYui** [comment]
OMG!! it works my data base was different thanx so much. you are the best!

**Comment by AdamGagorik** [comment]
Good to hear.  Maybe I need to update the default as the dark star project was forked and the name changed a few times.

**Comment by TeoTwawki** [comment]
> Good to hear. Maybe I need to update the default as the dark star project was forked and the name changed a few times.

we insisted on de-branding everything to stop any further name changing, so it should in theory never happen again. But might be best to remind ppl to edit their settings to point at whatever database name thy use, since that is customizable in the project anyway. But the default is just `xidb` now. Not really any different from ppl needing to use their own password.
