### ISSUE TITLE
AH expiry change in DarkStar

### ISSUE THREAD

**Issue by TeoTwawki** [AdamGagorik/pydarkstar#5]
Just a little heads up, they recently implemented expiration for unsold AH items (default is 3 days) and since then the automatically stocked items drop off the AH on their own. Had to roll back to an earlier copy of search server for now.

**Comment by AdamGagorik** [comment]
Do you think, or observe, items being restocked after some time?  The default restocking time of the broker was every hour.  Or is this issue deeper?

**Comment by TeoTwawki** [comment]
What I assumed happened was the broken's sale timestamp was in the past, because the AH was expiring them every hour, and the broker would re-list them. The result is a lot of wasted I/O while the 2 programs try to undo each others results.

**Comment by AdamGagorik** [comment]
Looks like I have it using the "current time" when stocking items.

```python
# manager.py
now = timeutils.timestamp(datetime.datetime.now())
```

From your description it would seem that things should be good for 3 real life days, but instead items are being expired almost immediately?  Seems odd.

* did they change the representation of dates in the AH table?

**Comment by TeoTwawki** [comment]
Not exactly immediately, just whenever the expiry check went off, so looks like it believed these were expired before the 3 days. Oh actually...I'm being dense. This was after serve had been down for updating, so the time was passing while it wasn't running. 

Still a bit of an annoyance even at 3hr intervals. I'm wondering if we can get away with setting the timestamp years into the future. @whasf can you shed some light on this, since you wrote the expiry code?

**Comment by AdamGagorik** [comment]
I just ```./broker.sh --refill items.csv``` on my server to see what would happen.  Items are stocked and stable for now, I'll check back later to see what happens.

I can easily add in an option to override the timestamp used, just let me know.

**Comment by TeoTwawki** [comment]
I guess I could change the actual AH's expiry to a really large value as well. I'd rather let players overpriced items get returned quickly while still letting the broker's items stay a long time though.

**Comment by whasf** [comment]
If you set the date in the db to super far in the future then it won't get expired out by my code.

**Comment by TeoTwawki** [comment]
Thanks Whasf.

**Comment by AdamGagorik** [comment]
I updated it to sale in the year 2525.  The client seems to have a max date its willing to display, but things are still buyable.

**Comment by TeoTwawki** [comment]
Thanks Adam.

**Comment by TeoTwawki** [comment]
Well damn. This has started happening since updating both pydarkstar and the search/AH server to current. This happens on a clean database and fresh clone of latest version pm github, tested this afternoon. 
```
[2015-03-11 13:07:27,270][ 6436][INFO ]: restocking...
[2015-03-11 13:07:27,280][ 6436][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\database.py", line 46, in scoped_session
    session.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 526, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 135, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 274, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 714, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 865, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1062, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 830, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 348, in check_error
    raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 116, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 109, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
DataError: (DataError) (1264, u"Out of range value for column 'date' at row 1") 'INSERT INTO auction_house (itemid, stack, seller, seller_name, date, price, buyer_name, sale, sell_date) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)' (2, 0, 0, 'AH-Bot', 17514144000.0, 4000, 'AH-Bot', 4000, 17514144000.0)
[2015-03-11 13:07:27,311][ 6436][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\database.py", line 46, in scoped_session
    session.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 526, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 135, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 274, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 714, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 865, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1062, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 830, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 348, in check_error
    raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 116, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 109, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
DataError: (DataError) (1264, u"Out of range value for column 'date' at row 1") 'INSERT INTO auction_house (itemid, stack, seller, seller_name, date, price, buyer_name) VALUES (%s, %s, %s, %s, %s, %s, %s)' (2, 0, 0, 'AH-Bot', 17514144000.0, 4000, None)
[2015-03-11 13:07:27,321][ 6436][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\pydarkstar\pydarkstar\database.py", line 46, in scoped_session
    session.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 526, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 135, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 274, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 714, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 865, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1062, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 830, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 348, in check_error
    raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 116, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 109, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
```
If needed, full log here: https://yadi.sk/d/A6IU2RONfBXGv

**Comment by AdamGagorik** [comment]
Looks like the year 2525 is **too far** in the future.

```python
DataError: (DataError) (1264, u"Out of range value for column 'date' at row 1") 'INSERT INTO auction_house (itemid, stack, seller, seller_name, date, price, buyer_name) VALUES (%s, %s, %s, %s, %s, %s, %s)' (2, 0, 0, 'AH-Bot', 17514144000.0, 4000, None)
```

I wonder if its MySQL rejecting that value for the date (17514144000) or darkstar sets a limit somewhere.  It would be nice to know the upper limit.

```python
adam@nuwork:~/Desktop/pydarkstar$ ipython
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pydarkstar.timeutils

In [2]: import datetime

In [3]: now = datetime.datetime.now()

In [4]: now
Out[4]: datetime.datetime(2015, 3, 11, 13, 8, 32, 461243)

In [5]: pydarkstar.timeutils.timestamp(now)
Out[5]: 1426079312.461243

In [6]: InTheYear2525 = datetime.datetime(2525, 1, 1)

In [7]: pydarkstar.timeutils.timestamp(InTheYear2525)
Out[7]: 17514144000.0
```

It seems a timestamp for 2525 is about a factor of 10 larger compared to a timestamp for 2015.  I will lower the date to year 2020, to see what happens.

I can make the sale date a parameter when I have more time later tonight, but still, knowing the upper bound would be nice.

**Comment by TeoTwawki** [comment]
No probs since you changed the datestamp again, so calling it fixed.
